apiVersion: v1
kind: Service
metadata:
  name: clientedb
  labels:
    app: clientedb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: clientedb
    tier: database
  clusterIP: None
